"""add trade status

Revision ID: 58a27f76229d
Revises: ee5b56abce97
Create Date: 2026-08-21 23:29:20.524898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a27f76229d'
down_revision: Union[str, Sequence[str], None] = 'ee5b56abce97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'trades',
    sa.Column(
        'status',
        sa.String(length=20),
        nullable=False,
        server_default='completed'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'status')
    # ### end Alembic commands ###
