"""add resource trade payment

Revision ID: ff2a43dc140d
Revises: 5e0457414257
Create Date: 2026-08-21 19:52:17.734552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2a43dc140d'
down_revision: Union[str, Sequence[str], None] = '5e0457414257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('payment_resource_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('payment_quantity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trades', 'resources', ['payment_resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'payment_quantity')
    op.drop_column('trades', 'payment_resource_id')
    # ### end Alembic commands ###
