"""
15-Round Sovereign Spotlight Configuration for Trade of Titans.
Each of the 15 official nations is featured in exactly one round with an
Economic Perk, Bonus Objective, and Reward.
Standby Alpha (Black Market) is strictly excluded.
"""

SPOTLIGHT_SCHEDULE = {
    1: {
        "country_name": "USA",
        "country_username": "usa",
        "title": "Petrodollar Hegemony",
        "perk": "+15% cash revenue on Grain and Electronics exports",
        "bonus_objective": "Conclude a bilateral trade pact with any Asian or European nation",
        "reward": "+$20,000 National Treasury Grant",
        "max_exports": 1,
        "max_imports": 1,
    },
    2: {
        "country_name": "Germany",
        "country_username": "germany",
        "title": "Precision Engineering",
        "perk": "Industrial Surge: Permitted 2 Exports this round instead of 1",
        "bonus_objective": "Export Steel and Electronics in the same round",
        "reward": "+150 Prestige Points",
        "max_exports": 2,
        "max_imports": 1,
    },
    3: {
        "country_name": "Canada",
        "country_username": "canada",
        "title": "Commonwealth Cordial",
        "perk": "Import Quota Discount: Needs 10% fewer units to fulfill strategic quotas",
        "bonus_objective": "Conclude an export deal with Australia, Italy, or France",
        "reward": "+$15,000 National Treasury Grant",
        "max_exports": 1,
        "max_imports": 1,
    },
    4: {
        "country_name": "Australia",
        "country_username": "australia",
        "title": "Mining Monopoly",
        "perk": "Uncapped Commodity Pricing: Gold and Livestock exports cannot be price-capped",
        "bonus_objective": "Export at least 1,000 units of Gold or Livestock",
        "reward": "+$20,000 National Treasury Grant",
        "max_exports": 1,
        "max_imports": 1,
    },
    5: {
        "country_name": "India",
        "country_username": "india",
        "title": "Pharmacy of the World",
        "perk": "Therapeutic Surge: Medicine and Spices export values increased by 25%",
        "bonus_objective": "Supply Medicine or Spices to any nation with <$250k treasury balance",
        "reward": "+120 Prestige Points",
        "max_exports": 1,
        "max_imports": 1,
    },
    6: {
        "country_name": "China",
        "country_username": "china",
        "title": "Belt & Road Surge",
        "perk": "Silk Route Subsidies: Importers purchasing from China receive a 0% tariff discount",
        "bonus_objective": "Complete bilateral trade deals with 2 different continents",
        "reward": "+$25,000 National Treasury Grant",
        "max_exports": 1,
        "max_imports": 1,
    },
    7: {
        "country_name": "Brazil",
        "country_username": "brazil",
        "title": "Amazonian Breadbasket",
        "perk": "Super-Barter: Permitted favorable 2:1 barter exchange ratio on Grain and Timber",
        "bonus_objective": "Fulfill at least 500 units of any national import quota",
        "reward": "+500 units of Steel",
        "max_exports": 1,
        "max_imports": 1,
    },
    8: {
        "country_name": "Russia",
        "country_username": "russia",
        "title": "Energy Dominance",
        "perk": "Petro-Sovereignty: Can demand Barter-Only (refuse cash) for Oil and Timber exports",
        "bonus_objective": "Secure an import deal for High-Tech Electronics or Medicine",
        "reward": "+$25,000 National Treasury Grant",
        "max_exports": 1,
        "max_imports": 1,
    },
    9: {
        "country_name": "Indonesia",
        "country_username": "indonesia",
        "title": "Spice Route Revival",
        "perk": "Maritime Monopoly: Spices and Textiles export values boosted by 30%",
        "bonus_objective": "Trade exclusively for Raw Industrial Materials (Oil, Steel, or Timber)",
        "reward": "+100 Prestige Points",
        "max_exports": 1,
        "max_imports": 1,
    },
    10: {
        "country_name": "Japan",
        "country_username": "japan",
        "title": "Robotics Vanguard",
        "perk": "Efficiency Multiplier: Electronics count 1.5x towards importer quota progress",
        "bonus_objective": "Import at least 1,000 units of Grain or Timber",
        "reward": "+150 Prestige Points",
        "max_exports": 1,
        "max_imports": 1,
    },
    11: {
        "country_name": "France",
        "country_username": "france",
        "title": "G7 Diplomatic Envoy",
        "perk": "Grand Alliance: Earns +10% cash bonus on all bilateral trade agreements",
        "bonus_objective": "Conclude an import without using the Black Market (Standby Alpha)",
        "reward": "+$20,000 National Treasury Grant",
        "max_exports": 1,
        "max_imports": 1,
    },
    12: {
        "country_name": "South Korea",
        "country_username": "south_korea",
        "title": "Semiconductor Titan",
        "perk": "Direct Barter Interchange: Can trade Electronics directly for Steel at 1:1 parity",
        "bonus_objective": "Fulfill 1 complete strategic import objective during this round",
        "reward": "+120 Prestige Points",
        "max_exports": 1,
        "max_imports": 1,
    },
    13: {
        "country_name": "Italy",
        "country_username": "italy",
        "title": "Renaissance Guilds",
        "perk": "Artisan Craft Premium: Textiles and Livestock earn a +20% luxury markup",
        "bonus_objective": "Export to a North American nation (USA, Canada, or Mexico)",
        "reward": "+$15,000 National Treasury Grant",
        "max_exports": 1,
        "max_imports": 1,
    },
    14: {
        "country_name": "Mexico",
        "country_username": "mexico",
        "title": "Nearshoring Hub",
        "perk": "Logistical Corridor: Permitted 2 Imports this round instead of 1",
        "bonus_objective": "Import Oil and Steel in the same round",
        "reward": "+150 Prestige Points",
        "max_exports": 1,
        "max_imports": 2,
    },
    15: {
        "country_name": "Saudi Arabia",
        "country_username": "saudi_arabia",
        "title": "OPEC Crown Jewel",
        "perk": "Energy Monopoly: Can set Oil export price up to 2.0x base reference price",
        "bonus_objective": "Export at least 2,000 units of Oil before the final trading whistle",
        "reward": "+$30,000 Grand Bounty",
        "max_exports": 1,
        "max_imports": 1,
    },
}


def get_round_spotlight(round_number: int) -> dict | None:
    """Returns the sovereign spotlight configuration for the given round number (1-15)."""
    return SPOTLIGHT_SCHEDULE.get(round_number)
